### PR TITLE
Add support to Py3.8 thanks to meshcat 0.1.1

### PR DESCRIPTION
**Pull request by dcambie**
Thanks to Meshcat>0.1.1 supporting Py38+

Actually, pvtrace also works well with Python 3.9 on linux now, so maybe python_requires could be <3.10.  However, there are currently no xxhash wheels available for Windows (issue ifduyue/python-xxhash#43) nor it is available on conda and it needs to be compiled, so not easy for random users...

### CODE REVIEW

**Comment by danieljfarrell** [comment]
Great changes, thanks for updating everything!

I think there are some `skipif` decorators on the rendering tests for Windows. Do they now pass?

**Comment by danieljfarrell** [comment]
Is it possible to target develop? Don’t worry if not, I’m using git flow, so I usually start releases from develop branch.

**Comment by danieljfarrell** [comment]
Thanks @dcambie ! I've merged into develop!

**Comment by dcambie** [comment]
> 
> 
> Great changes, thanks for updating everything!
> 
> I think there are some `skipif` decorators on the rendering tests for Windows. Do they now pass?

Good question, I'll check those!
P.S. Sorry for targeting master and not develop, next time I'll do it right:)

**Comment by danieljfarrell** [comment]
No problem, I logged in with my phone and could not see an option to change, but it was obvious when using the desktop site!

**Comment by danieljfarrell** [comment]
I think I did it! Test pass, one weird issue, but I think it is solved in the CLU branch so will just wait for that. 

If you have anything else you want to add it can go here, https://github.com/danieljfarrell/pvtrace/tree/release/2.1.7 otherwise, I'll merge this to master and make a new release in a few days.

**Pull request merged**
